#!/bin/bash

(
    cd website ; jekyll build ; ./local.sh
    rsync -qrc --delete _site/  /home/web/pokey.goestheweasel.com/
    chown -R admpokey:www-data /home/web/pokey.goestheweasel.com
    (find /home/web/pokey.goestheweasel.com -type f -print0|xargs -0 chmod 640)
    (find /home/web/pokey.goestheweasel.com -type d -print0|xargs -0 chmod 750)
        
)| slacktell --channel=#deployment --pretext="Pokey nabtso Deployment"

